#docker run -d --rm --name mongo -p 27017:27017 -v mongodbdata:/data/db mongo
#docker-compose up (to run this)

version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      # left port - internal, right - external
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
